### ISSUE TITLE
Cannot run local server

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/PaddlePaddle.org#340]
I followed instructions in https://github.com/PaddlePaddle/PaddlePaddle.org/blob/develop/README.md to run a local Web server in a Docker container.  However, the `docker run` command prompts me some error messages about the "secret key":

```
[2017-11-23 00:34:43 +0000] [48] [INFO] Worker exiting (pid: 48)
[2017-11-23 00:34:43 +0000] [47] [INFO] Worker exiting (pid: 47)
[2017-11-23 00:34:43 +0000] [53] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/var/www/portal/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/portal/settings.py", line 23, in <module>
    SECRET_KEY = os.environ['SECRET_KEY']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SECRET_KEY'
[2017-11-23 00:34:43 +0000] [53] [INFO] Worker exiting (pid: 53)
```

**Comment by varunarora** [comment]
Very valid concern.

@cs2be Could we please add a small bit in our documentation of the environment variables we need to pass in when building our docker?
