### ISSUE TITLE
Fail to create web viewer based on guide

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/PaddlePaddle.org#484]
According to the doc, I can use the following command to create doc viewer
```
docker run -it -p 8000:8000 paddlepaddle/paddlepaddle.org:latest
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/var/www/portal/portal/wsgi.py", line 32, in <module>
    if os.environ['ENV'] == 'release':
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
```

I changed to
```
docker run -e ENV='release' -it -p 8000:8000 -v `pwd`:/var/content paddlepaddle/paddlepaddle.org:latest
```
However, I got:
```
Bad Request (400)
```

**Comment by jetfuel** [comment]
Hi @panyx0718, Can you try the following please? This should allow you to use the viewer.  
```
docker run -e ENV='' -it -p 8000:8000 -v `pwd`:/var/content paddlepaddle/paddlepaddle.org:latest
```

I will create an issue for this so there is no need to set ENV='' manually.

**Comment by jetfuel** [comment]
If the docker image is not stable, please revert back to use this method. 

```
mkdir paddlepaddle # Create paddlepaddle working directory
cd paddlepaddle

# Clone the content repositories and PaddlePaddle.org
git clone https://github.com/PaddlePaddle/Paddle.git
git clone https://github.com/PaddlePaddle/book.git
git clone https://github.com/PaddlePaddle/models.git
git clone https://github.com/PaddlePaddle/Mobile.git
git clone https://github.com/PaddlePaddle/PaddlePaddle.org.git

# Please specify the PaddlePaddle working directory. In the current setting, it should be pwd
export CONTENT_DIR=<path_to_paddlepaddle_working_directory>
export ENV=''

cd PaddlePaddle.org/portal/
pip install -r requirements.txt
python manage.py runserver
```
